# Example OpenAPI spec using YAML
# Be aware that YAML has indentation based scoping.
# https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
# Generate client & server code stubs using http://editor.swagger.io/#/
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Simple Example API

# Describe your paths here
paths:
  # This is the version path endpoint.
  /version:
    # This is a HTTP operation (GET)
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        get the name and version string
      produces:
      - application/json
      responses:
        # Response code
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Version'

  # This is an example object endpoint. Change it.
  /example:
    get:
      description: |
        get an example object
      operationId: getExample
      produces:
      - application/json
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/Example'
    post:
      description: |
        post an example object
      operationId: addExample
      consumes:
      - application/json
      parameters:
      - in: body
        name: body
        description: Example object that needs to be added
        required: false
        schema:
          $ref: "#/definitions/Example"

      responses:
        200:
          description: example post successful
        400:
          description: example post not successful, bad request.

definitions:
  Version:
    title: Version Object
    type: object
    properties:
      serviceId:
        type: string
      version:
        type: string
  Example:
    title: Example Object
    type: object
    properties:
      prop1:
        type: string
      prop2:
        type: integer
